# Generated by Django 5.0.4 on 2024-05-02 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_tag_doc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doc.group'),
        ),
    ]
