# Generated by Django 5.0.4 on 2024-05-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_tag_is_group_alter_tag_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
