# Generated by Django 5.0.4 on 2024-05-10 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_group_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='doc_id',
        ),
        migrations.AddField(
            model_name='tag',
            name='doc_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='doc.document'),
        ),
    ]
