# Generated by Django 5.0.4 on 2024-05-12 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0006_remove_tag_doc_id_tag_doc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fiche_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('id_fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.fiche')),
            ],
        ),
        migrations.CreateModel(
            name='List_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('typ', models.CharField(max_length=50)),
                ('id_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.liste')),
            ],
        ),
    ]
