# Generated by Django 5.0.4 on 2024-05-16 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0008_remove_document_content_id_remove_document_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 16, 12, 31, 6, 541391, tzinfo=datetime.timezone.utc), verbose_name='date creation'),
        ),
    ]
