# Generated by Django 5.0.4 on 2024-05-16 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0009_document_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date creation'),
        ),
    ]
