# Generated by Django 5.0.4 on 2024-05-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0011_metadoc_document_meta_doc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('content', models.TextField()),
            ],
        ),
    ]
